### ISSUE TITLE
该程序运行异常

### ISSUE THREAD

**Issue by chy10403** [gang544043963/TabBarControllerJumpDemo#1]
//偷梁换柱在这里……
- (void)viewDidAppear:(BOOL)animated{
  [super viewDidAppear:animated];
  
  [UIManager sharedInstance].tabbarViewController.selectedIndex = 0;
  [self.navigationController setViewControllers:@[[UIManager sharedInstance].tabbarViewController,self]];
  }

**Comment by gang544043963** [comment]
bug fixed!
